// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: otp_queries.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addOTP = `-- name: AddOTP :one
insert into otps
(user_id) values ($1)
returning id, user_id, otp, created_at, expires_at
`

func (q *Queries) AddOTP(ctx context.Context, userID uuid.UUID) (Otp, error) {
	row := q.queryRow(ctx, q.addOTPStmt, addOTP, userID)
	var i Otp
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Otp,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteOTPByEmail = `-- name: DeleteOTPByEmail :execresult
delete from otps
where user_id = (select user_id from users where email = $1)
`

func (q *Queries) DeleteOTPByEmail(ctx context.Context, email string) (sql.Result, error) {
	return q.exec(ctx, q.deleteOTPByEmailStmt, deleteOTPByEmail, email)
}

const getValidOTPByUserID = `-- name: GetValidOTPByUserID :one
SELECT id, user_id, otp, created_at, expires_at FROM otps
WHERE user_id = $1 and expires_at > current_timestamp
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetValidOTPByUserID(ctx context.Context, userID uuid.UUID) (Otp, error) {
	row := q.queryRow(ctx, q.getValidOTPByUserIDStmt, getValidOTPByUserID, userID)
	var i Otp
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Otp,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
